spring:
  profiles : default
  data:
    mongodb:
      uri: mongodb://localhost:27017/ALLIE?connectTimeoutMS=10000&socketTimeoutMS=5000
logging:
  file: C:\allie\logs\dev_app.log
  level:
    guru.springframework.controllers: DEBUG
    org.hibernate: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
---
spring:
  profiles : DEV
  data:
    mongodb:
      uri: mongodb://ec2-52-39-103-175.us-west-2.compute.amazonaws.com:27017/ALLIE?connectTimeoutMS=10000&socketTimeoutMS=5000
logging:
  file: /allie/logs/allie-data.log
  level:
    guru.springframework.controllers: DEBUG
    org.hibernate: DEBUG
    org.springframework.web: DEBUG
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"
---
spring:
  profiles : DEVTEST
  data:
    mongodb:
      uri: mongodb://ec2-52-39-103-175.us-west-2.compute.amazonaws.com:27017/TEST?connectTimeoutMS=10000&socketTimeoutMS=5000
logging:
  file: /allie/logs/allie-data.log
  level:
    guru.springframework.controllers: DEBUG
    org.hibernate: DEBUG
    org.springframework.web: DEBUG
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"
---
spring:
  profiles : TEST
  data:
    mongodb:
      uri: mongodb://localhost:27017/test?connectTimeoutMS=10000&socketTimeoutMS=5000
      #uri: mongodb://${MONGO_USER}:${MONGO_PWD}@lxv1114.allstate.com:27000/UCVDB-ITEST?connectTimeoutMS=10000&socketTimeoutMS=5000
logging:
  file: C:\allie\logs\dev_app.log
  level:
    guru.springframework.controllers: DEBUG
    org.hibernate: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"

