--- 
files: 
  -
    source: source
    destination: /var/allie-data/
  -
    source: config
    destination: /var/allie-data/config/
hooks:
  ApplicationStop:
      -
        location: deploy_hooks/stop-service.sh
        runas: root
        timeout: 3600
  BeforeInstall:
    -
      location: deploy_hooks/rename-deployable.sh
      runas: root
      timeout: 3600
  AfterInstall:
    -
      location: deploy_hooks/set-environment.py
      runas: root
      timeout: 3600
  ApplicationStart:
    -
      location: deploy_hooks/symbolic-service.sh
      runas: root
      timeout: 3600
os: linux
version: 0.0